allChelseaPlayers <- (rbind(ChelseaFirstTeam_04,
                            ChelseaFirstTeam_05,
                            ChelseaFirstTeam_06,
                            ChelseaFirstTeam_07,
                            ChelseaFirstTeam_08,
                            ChelseaFirstTeam_09,
                            ChelseaFirstTeam_10, 
                            ChelseaFirstTeam_11, 
                            ChelseaFirstTeam_12, 
                            ChelseaFirstTeam_13, 
                            ChelseaFirstTeam_14, 
                            ChelseaFirstTeam_15, 
                            ChelseaFirstTeam_16, 
                            ChelseaFirstTeam_17, 
                            ChelseaFirstTeam_18, 
                            ChelseaFirstTeam_19, 
                            ChelseaU23_19, 
                            ChelseaU23s_18, 
                            ChelseaU23s_17, 
                            ChelseaU23_16, 
                            ChelseaU23_15,
                            ChelseaU23_14,
                            ChelseaU23_13,
                            ChelseaU23_12,
                            ChelseaU23_11,
                            ChelseaU23_10,
                            ChelseaU23_09,
                            ChelseaU23_08,
                            ChelseaU23_07,
                            ChelseaU23_06,
                            ChelseaU23_05,
                            ChelseaU23_04))

write.csv(allChelseaPlayers, file="C:/Users/peter/Desktop/PlayerData/AllChelseaPlayers.csv")


allCityPlayers <-    (rbind(ManCityFirstTeam_04,
                            ManCityFirstTeam_05,
                            ManCityFirstTeam_06,
                            ManCityFirstTeam_07,
                            ManCityFirstTeam_08,
                            ManCityFirstTeam_09,
                            ManCityFirstTeam_10, 
                            ManCityFirstTeam_11, 
                            ManCityFirstTeam_12, 
                            ManCityFirstTeam_13, 
                            ManCityFirstTeam_14, 
                            ManCityFirstTeam_15, 
                            ManCityFirstTeam_16, 
                            ManCityFirstTeam_17, 
                            ManCityFirstTeam_18, 
                            ManCityFirstTeam_19, 
                            ManCityU23_19, 
                            ManCityU23_18, 
                            ManCityU23_17, 
                            ManCityU23_16, 
                            ManCityU23_15,
                            ManCityU23_14,
                            ManCityU23_13,
                            ManCityU23_12,
                            ManCityU23_11,
                            ManCityU23_10,
                            ManCityU23_09,
                            ManCityU23_08,
                            ManCityU23_07,
                            ManCityU23_06,
                            ManCityU23_05,
                            ManCityU23_04))

write.csv(allCityPlayers, file="C:/Users/peter/Desktop/PlayerData/Manchester City/AllCityPlayers.csv")


allUtdPlayers <-    (rbind(ManUtdFirstTeam_04,
                            ManUtdFirstTeam_05,
                            ManUtdFirstTeam_06,
                            ManUtdFirstTeam_07,
                            ManUtdFirstTeam_08,
                            ManUtdFirstTeam_09,
                            ManUtdFirstTeam_10, 
                            ManUtdFirstTeam_11, 
                            ManUtdFirstTeam_12, 
                            ManUtdFirstTeam_13, 
                            ManUtdFirstTeam_14, 
                            ManUtdFirstTeam_15, 
                            ManUtdFirstTeam_16, 
                            ManUtdFirstTeam_17, 
                            ManUtdFirstTeam_18, 
                            ManUtdFirstTeam_19, 
                            ManUtdU23_19, 
                            ManUtdU23_18, 
                            ManUtdU23_17, 
                            ManUtdU23_16, 
                            ManUtdU23_15,
                            ManUtdU23_14,
                            ManUtdU23_13,
                            ManUtdU23_12,
                            ManUtdU23_11,
                            ManUtdU23_10,
                            ManUtdU23_09,
                            ManUtdU23_08,
                            ManUtdU23_07,
                            ManUtdU23_06,
                            ManUtdU23_05,
                            ManUtdU23_04))

write.csv(allUtdPlayers, file="C:/Users/peter/Desktop/PlayerData/Manchester United/AllUnitedPlayers.csv")

allLiverpoolPlayers <-    (rbind(LiverpoolFirstTeam_04,
                           LiverpoolFirstTeam_05,
                           LiverpoolFirstTeam_06,
                           LiverpoolFirstTeam_07,
                           LiverpoolFirstTeam_08,
                           LiverpoolFirstTeam_09,
                           LiverpoolFirstTeam_10, 
                           LiverpoolFirstTeam_11, 
                           LiverpoolFirstTeam_12, 
                           LiverpoolFirstTeam_13, 
                           LiverpoolFirstTeam_14, 
                           LiverpoolFirstTeam_15, 
                           LiverpoolFirstTeam_16, 
                           LiverpoolFirstTeam_17, 
                           LiverpoolFirstTeam_18, 
                           LiverpoolFirstTeam_19, 
                           LiverpoolU23_19, 
                           LiverpoolU23_18, 
                           LiverpoolU23_17, 
                           LiverpoolU23_16, 
                           LiverpoolU23_15,
                           LiverpoolU23_14,
                           LiverpoolU23_13,
                           LiverpoolU23_12,
                           LiverpoolU23_11,
                           LiverpoolU23_10,
                           LiverpoolU23_09,
                           LiverpoolU23_08,
                           LiverpoolU23_07,
                           LiverpoolU23_06))

write.csv(allLiverpoolPlayers, file="C:/Users/peter/Desktop/PlayerData/Liverpool/AllLiverpoolPlayers.csv")


write.csv(rbind(allChelseaPlayers, allCityPlayers, allUtdPlayers, allLiverpoolPlayers), "C:/Users/peter/Desktop/PlayerData/AllPlayers.csv")
